apiVersion: apps/v1
kind: Deployment
metadata:
  name: fight2-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fight2
  template:
    metadata:
      labels:
        app: fight2
    spec:
      containers:
      - name: fight2
        image: nicoletrinity/fight2.js
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: MONGO_URL
          value: "mongodb://mongodb-service:27017"
        - name: PORT
          value: "8080"
        volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secrets"
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: oauth-client-secret
---
apiVersion: v1
kind: Service
metadata:
  name: fight2-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  selector:
    app: fight2
